apiVersion: apps/v1
kind: Deployment
metadata:
  name: gfj-frontend
  namespace: gfj-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gfj-frontend
  template:
    metadata:
      labels:
        app: gfj-frontend
    spec:
      containers:
        - name: gfj-frontend
          image: chankyswami/gfj-frontend:git-initial
          ports:
            - containerPort: 80